### ISSUE TITLE
Topology is self-intersecting

### ISSUE THREAD

**Issue by basteks** [fferrin/pytopojson#7]
While trying to use the pytopojson library, I faced a problem on a simple geometry (see bellow) : 

![model](https://user-images.githubusercontent.com/64981563/112004475-202e8280-8b22-11eb-8727-5c47ddda16ad.png)

with a very simple input (see [input.geojson.txt](https://github.com/fferrin/pytopojson/files/6182717/input.geojson.txt), Features are ABCH, GDEF, HILG and JCDK ), the result of 
```
topology_ = topology.Topology()
topojson = topology_({'my_geojson': feature_collection})
```
is self-intersecting (see [output.topojson.txt](https://github.com/fferrin/pytopojson/files/6182719/output.topojson.txt)). Arcs are indeed :
- ABC
- CH
- HA
- GD
- DEFG
- HILG
- GH
- JC
- CD
- DKJ

Did I miss something, or is the process wrong ? As far as I understand, I should get following arcs :
- HABC
- DEFG
- HI
- IL
- LG
- GH
- IJ
- LK
- JC
- CD
- DK
- KJ

**Comment by fferrin** [comment]
Thanks @basteks  for reporting this! I'll take a look later today. If you can share the GeoJSON in this ticket, it'd be helpful. Otherwise, I'll try with points with values in `0, 1, 2, ...`

**Comment by basteks** [comment]
Thanks for your answer @fferrin ! Normally you can find the input file in my previous message, there's a link just bellow the figure that points to input.geojson.txt, I converted it to txt as github aparently didn't accept .json, but the file is ok. Let me know if you encounter problems with the file...

**Comment by fferrin** [comment]
@basteks I just saw the file :upside_down_face: After looking at the input and output files, the first thing I can tell you is that the results are ok (you can check it by uploading your file to [this website](http://geojson.io/) and save it as a TopoJSON or installing Mike Bostock's [topojson-client](https://github.com/topojson/topojson-client/blob/master/README.md#installing) and compare the two files).

Something to note is that the website also quantizes the geometry, so the results are different, but if you upload both to the website, you will see that they are the same. In this case, quantization is not a good option because it increases the size of the file, but that's not a big problem.

Now on your question, there are some misconceptions about how this works. I'd suggest you to read [Mike Bostock's explanation](https://bost.ocks.org/mike/topology/) of how he implemented this extension. If you go to [section 2](https://bost.ocks.org/mike/topology/#join), after the image, you will see a note that says lines or polygons are splitted only if they share points. If they intersect but don't share a point, then that point won't be a junction: This is why you don't see `IL`, `IJ`, `LK` and `KJ` arcs.

Another thing to note is that, for topology, lines and polygons are not the same: Polygons can be rotated to choose a junction as the start and end point (for example), but the start and end point of the a line can not be changed. That's why you can see more arcs if you use lines (for future ocassions).

Finally, if you want to do it by hand, I suggest you to follow the four steps in the explanation but bearing in mind that you are working with lines, not with polygons, so, for example, `KJC` will not be a valid arc but `JC` will.

Hope this helps you. If you have any further questions, please let me know to see if I can help you. Otherwise, feel free to close this issue

**Comment by basteks** [comment]
Hello @fferrin and thank you very much for you answer ! Yesterday I looked at the link you mentioned trying to manually code the process using [the Shapely lib](https://shapely.readthedocs.io/en/stable/), I stopped on this particular sentence on section 2 after the image, read it twice, but didn't manage to follow the thread of my thoughts until the conclusion that the output wasn't what I was expecting, because the **input** wasn't what the algorithm was waiting for, damn slow brain !! :smile: 
Anyway, I understand why it's not working as I was expecting, and realize with your answer that I still have two options for my problem : creating the whole TopoJSON myself after recoding the whole Mike Bostock's process (which I already started), or inserting junction points in the GeoJSON feature and generating the TopoJSON from your algorithm (maybe easier ?)

**Comment by fferrin** [comment]
So you need a TopoJSON with those particular arcs? I think you can edit the output file to match the arcs that you expect and then play a little with the indexes in each geometry until you reproduce the 4 squares. Let me know if I can do anythinig else for you! I'll be glad to help
